<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_Application/SOA_Project_1/ObtenerPolizasDeCliente" name="ObtenerPolizasDeCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_Application/SOA_Project_1/ObtenerPolizasDeCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_Application/SOA_Project_1/ObtenerPolizasDeCliente" location="../Resources/WSDL/ObtenerPolizasDeCliente.wsdl"/>
  <binding name="ObtenerPolizasDeCliente_ptt-binding" type="tns:ObtenerPolizasDeCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ObtenerPolizasDeCliente">
      <soap:operation soapAction="ObtenerPolizasDeCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ObtenerPolizasDeCliente-service">
    <port name="ObtenerPolizasDeCliente-port" binding="tns:ObtenerPolizasDeCliente_ptt-binding">
      <soap:address location="jca://eis/DB/grupo_hogar"/>
    </port>
  </service>
</definitions>